# Generated by Django 3.2.5 on 2022-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='OrderItem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='OrderItem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
