# Generated by Django 3.2.5 on 2022-06-22 09:21

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220622_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name=cart.models.OrderItem),
        ),
    ]
