# Generated by Django 3.2.5 on 2022-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0005_auto_20220622_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='OrderItem',
            name='item',
        ),
        migrations.AddField(
            model_name='OrderItem',
            name='item',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
