# Generated by Django 3.2.5 on 2022-06-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20220623_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='OrderItem',
            old_name='product',
            new_name='item',
        ),
    ]
