# Generated by Django 3.2 on 2022-06-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, max_length=100, to='cart.OrderItem'),
        ),
    ]
